spring:
  application:
    name: service-auth
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-cloud-auth?serverTimezone=Australia/Sydney
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  servlet:
    context-path: /uas
  port: 5000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
